{
 "title": "Loadgen (debug)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "test_id",
    "label": "test_id",
    "query": {}
   },
   {
    "name": "test_group",
    "label": "test_group",
    "query": {}
   },
   {
    "name": "go_test_name",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Responses stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS per stages",
   "type": "timeseries",
   "description": "RPS per stages",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time({cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"stats\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}\n| json\n| unwrap current_rps[$__interval])",
     "legendFormat": "Stage"
    }
   ]
  },
  {
   "title": "Quantiles over groups (99, 95, 50)",
   "type": "timeseries",
   "description": "Quantiles over groups (99, 95, 50)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}\n| json\n| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "Q 99 - {{error}}"
    },
    {
     "expr": "quantile_over_time(0.95, {cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", test_name=\"TestLokiReporting/can_report_a_batch\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}\n| json\n| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "Q 95 - {{error}}"
    },
    {
     "expr": "quantile_over_time(0.50, {cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", test_name=\"TestLokiReporting/can_report_a_batch\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}\n| json\n| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "Q 50 - {{error}}"
    }
   ]
  },
  {
   "title": "Responses by types over time",
   "type": "timeseries",
   "description": "Responses by types over time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "last_over_time({cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}\n| json\n| unwrap duration [$__interval]) / 1e6"
    }
   ]
  },
  { "title": "Debug data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Generator stats",
   "type": "logs",
   "description": "Generator stats",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{cluster=\"sdlc\", env=\"chainlink-test\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"stats\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"}"
    }
   ]
  },
  {
   "title": "Failed responses",
   "type": "logs",
   "description": "Failed responses",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{cluster=\"sdlc\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"} |= \"failed\\\":true\""
    }
   ]
  },
  {
   "title": "Timed out responses",
   "type": "logs",
   "description": "Timed out responses",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{cluster=\"sdlc\", app=\"chainlink\", go_test_name=\"${go_test_name:pipe}\", test_data_type=\"responses\", test_group=\"$test_group\", test_id=~\"${test_id:pipe}\"} |= \"timeout\\\":true\""
    }
   ]
  }
 ]
}