#!/bin/bash

# Find all 'go.mod' files, get their directories, and run 'go mod tidy'
find "./" -type f -name 'go.mod' -print0 | while IFS= read -r -d $'\0' file; do
    directory=$(dirname "$file")
    cd "$directory" || exit 1

    # Run linter and capture exit status
    set +e
    golangci-lint run -v
    linting_result=$?
    set -e

    # Check linting result
    if [[ $linting_result -ne 0 ]]; then
        echo -e "Executing linters in $directory... \e[31mNOK!\e[0m\n"
        echo -e "Run \`cd $directory && golangci-lint run --fix -v\` and fix the issues\n"
        exit 1
    else
        echo -e "Executing linters in $directory... \e[32mOK!\e[0m\n"
    fi
    cd - || exit 1
done
