#!/bin/bash

set +e

# Find all 'go.mod' files, get their directories, and run 'go mod tidy'
find "./" -type f -name 'go.mod' -print0 | while IFS= read -r -d $'\0' file; do
    dir=$(dirname "$file")
    echo "Executing cd \"$dir\" && go mod tidy"
    cd "$dir" || exit 1
    go mod tidy
    cd - || exit 1
done

# pre-commit stashes changes before running the hooks so we can use git to check for changes here
# Run git diff and capture output
output=$(git diff --stat)

if [ -z "$output" ]; then
    echo "No changes in any files."
else
    echo "go.mod files that need to be tidied:"
    echo "$output" | awk -F '|' '/\|/ { print $1 }'
    exit 1
fi
