#!/bin/bash

set -e

# Find all 'go.mod' files, excluding the 'seth' directory, get their directories, and run an empty 'go test' in them to compile the tests.
# Seth is excluded because it can't be tested like this, env vars are required and setup
find "./" -path "./seth" -prune -o -type f -name 'go.mod' -print0 | while IFS= read -r -d $'\0' file; do
    dir=$(dirname "$file")
    echo "Executing cd \"$dir\" && go test -run=^# ./..."
    cd "$dir"
    go test -run=^# ./...
    cd -
done