#!/bin/bash

printf "\n\e[37m*** Running Pre-push unit test hook ***\e[0m\n"

printf "Executing unit tests..."

make test_unit > /dev/null 2>&1
unit_test_result=$?

if [[ $unit_test_result -ne 0 ]];
then
    printf "Executing unit tests... ❌\n"
    printf "Run 'make test_unit' to verify after you fix them.\n"
    exit 1
else
    printf "Executing unit tests... ✅\n"
fi

printf "\n\e[37m*** All good! ***\e[0m\n\n"
