FROM golang:alpine

WORKDIR /compilation
RUN apk add build-base
ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go test -c ./suite/soak/tests -o remote.test