#!/usr/bin/env bash

# Generates go.md

set -e

echo "## CTF modules and org dependencies
\`\`\`mermaid
flowchart LR
"
gomods graph | modgraph -prefix github.com/smartcontractkit/chainlink-testing-framework/
echo "\`\`\`"
