{
 "title": "WASP Load Test",
 "tags": [
  "generated",
  "load-test"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "go_test_name", "label": "go_test_name", "query": "label_values(go_test_name)" },
   { "name": "gen_name", "label": "gen_name", "query": "label_values(gen_name)" },
   { "name": "branch", "label": "branch", "query": "label_values(branch)" },
   { "name": "commit", "label": "commit", "query": "label_values(commit)" },
   { "name": "call_group", "label": "call_group", "query": "label_values(call_group)" }
  ]
 },
 "panels": [
  {
   "title": "WASP Load Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS (Now)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_rps [1s]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    }
   ]
  },
  {
   "title": "VUs (Now)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_instances [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Now)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} [1s])) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} Responses/sec"
    }
   ]
  },
  {
   "title": "Successful requests (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\n\t\t\tsum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap success [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)\n\t\t\t",
     "legendFormat": "{{go_test_name}} {{gen_name}} Successful requests"
    }
   ]
  },
  {
   "title": "Errored requests (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\n\t\t\tsum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap failed [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)\n\t\t\t",
     "legendFormat": "{{go_test_name}} {{gen_name}} Errored requests"
    }
   ]
  },
  {
   "title": "Timed out requests (Total)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\n\t\t\tsum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap callTimeout [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)\n\t\t\t",
     "legendFormat": "{{go_test_name}} {{gen_name}} Timed out requests"
    }
   ]
  },
  {
   "title": "RPS/VUs per schedule segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "\n\t\t\tmax_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_rps [$__interval]) by (node_id, go_test_name, gen_name)\n\t\t\t",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    },
    {
     "expr": "\n\t\t\tsum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_rps [$__interval]) by (node_id, go_test_name, gen_name))\n\t\t\t",
     "legendFormat": "{{go_test_name}} Total RPS"
    },
    {
     "expr": "\n\t\t\tmax_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_instances [$__interval]) by (node_id, go_test_name, gen_name)\n\t\t\t",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    },
    {
     "expr": "\n\t\t\tsum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t| json\n\t\t\t| unwrap current_instances [$__interval]) by (node_id, go_test_name, gen_name))\n\t\t\t",
     "legendFormat": "{{go_test_name}} Total VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Responses" } },
   "targets": [
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\", call_group=~\"${call_group:pipe}\"} [1s])) by (node_id, go_test_name, gen_name, call_group)",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} responses/sec"
    },
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} [1s])) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} Total responses/sec"
    }
   ]
  },
  {
   "title": "Latency quantiles over groups (99, 95, 50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n\t\t\t\tquantile_over_time(0.99, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t\t| json\n\t\t\t\t| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 99 - {{error}}"
    },
    {
     "expr": "\n\t\t\t\tquantile_over_time(0.95, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t\t| json\n\t\t\t\t| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 95 - {{error}}"
    },
    {
     "expr": "\n\t\t\t\tquantile_over_time(0.50, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t\t| json\n\t\t\t\t| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 50 - {{error}}"
    }
   ]
  },
  {
   "title": "Responses latencies by types over time (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n\t\t\t\tlast_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\", call_group=~\"${call_group}\"}\n\t\t\t\t| json\n\t\t\t\t| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} T: {{timeout}} E: {{error}}"
    },
    {
     "expr": "\n\t\t\t\tlast_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n\t\t\t\t| json\n\t\t\t\t| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} all groups T: {{timeout}} E: {{error}}"
    }
   ]
  },
  {
   "title": "WASP Load Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest segment stats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\n                sum(bytes_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", gen_name=~\"${gen_name:pipe}\"} [$__range]) * 1e-6)\n                ",
     "legendFormat": "Overall logs size"
    },
    {
     "expr": "\n                sum(bytes_rate({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", gen_name=~\"${gen_name:pipe}\"} [$__interval]) * 1e-6)\n                ",
     "legendFormat": "Logs size per second"
    }
   ]
  },
  {
   "title": "CallResult sampling (successful results)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "\n                sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n                | json\n                | unwrap samples_recorded [$__interval])) by (go_test_name, gen_name)\n                ",
     "legendFormat": "{{go_test_name}} {{gen_name}} recorded"
    },
    {
     "expr": "\n                sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n                | json\n                | unwrap samples_skipped [$__interval])) by (go_test_name, gen_name)\n                ",
     "legendFormat": "{{go_test_name}} {{gen_name}} skipped"
    }
   ]
  },
  {
   "title": "Stats logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}"
    }
   ]
  },
  {
   "title": "Failed responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} |~ \"failed\\\":true\""
    }
   ]
  },
  {
   "title": "Timed out responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} |~ \"timeout\\\":true\""
    }
   ]
  }
 ]
}