{
 "title": "Workflow Engine",
 "tags": [
  "Node",
  " Workflows",
  " Capabilities",
  " Resources",
  " Performance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Workflow Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs Volume",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (level) (\n  count_over_time(\n    {job=\"ctf\"}\n    |~ \"workflowID\"\n    | logfmt\n    | label_format level=`{{ if or (contains \"failed\" .msg) (hasPrefix \"error executing step request\" .msg) }}error{{ else }}info{{ end }}`\n    [$__interval]\n  )\n)\n",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Workflow Logs (error)",
   "type": "logs",
   "description": "Workflow Logs (error)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{job=\"ctf\"}\n  |~ \"workflowID\"\n  | json\n  | level=\"error\"\n  | line_format `level={{.level}} ts={{.ts}} logger={{.logger}} caller={{.caller}} msg=\"{{.msg}}\" version={{.version}} workflowID={{.workflowID}} stepRef={{.stepRef}} workflowExecutionID={{.workflowExecutionID}} state={{.state}}`"
    }
   ]
  },
  {
   "title": "Workflow Logs (info)",
   "type": "logs",
   "description": "Workflow Logs (info)",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"ctf\"}\n  |~ \"workflowID\"\n  | json\n  | level=\"info\"\n  | line_format `level={{.level}} ts={{.ts}} logger={{.logger}} caller={{.caller}} msg=\"{{.msg}}\" version={{.version}} workflowID={{.workflowID}} stepRef={{.stepRef}} workflowExecutionID={{.workflowExecutionID}} state={{.state}}`"
    }
   ]
  },
  {
   "title": "Workflows Logs (debug)",
   "type": "logs",
   "description": "Workflows Logs (debug)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"ctf\"}\n  |~ \"workflowID\"\n  | json\n  | level=\"debug\"\n  | line_format `level={{.level}} ts={{.ts}} logger={{.logger}} caller={{.caller}} msg=\"{{.msg}}\" version={{.version}} workflowID={{.workflowID}} stepRef={{.stepRef}} workflowExecutionID={{.workflowExecutionID}} state={{.state}}`"
    }
   ]
  },
  {
   "title": "Workflow Custom Messages",
   "type": "logs",
   "description": "Workflow Custom Messages",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service:chainlink\"} !~ \"heartbeat\"\n| json | __error__ = \"\""
    }
   ]
  },
  {
   "title": "Beholder Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heartbeat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "expr": "heartbeat_count{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "App Version",
     "type": "stat",
     "description": "app version",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "heartbeat_count{}", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Workflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Nodes Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(platform_engine_workflow_count{}) by (csa_public_key))"
    }
   ]
  },
  {
   "title": "Running Workflows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(group(platform_engine_workflow_count{}) by (workflowID))"
    }
   ]
  },
  {
   "title": "Running Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "group by (workflowName, workflowID) (sum(platform_engine_workflow_count{}) by (workflowName, workflowID))",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflow Errors over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(platform_engine_workflow_errors_total{}[$__range])) by (workflowName, workflowID) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unregistered Workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (workflowID, workflowName) (platform_engine_workflow_unregistered_count_total{})",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflows Execution Rate | Status: Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workflowName) (\n  increase(\n    platform_engine_workflow_completed_time_seconds_count{}[1m]\n  )\n) / (\n  sum by (workflowName) (\n    increase(\n      platform_engine_workflow_completed_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_earlyexit_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_error_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_timeout_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Workflows by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "group by (workflowName, workflowID) (rate(platform_engine_workflow_completed_time_seconds_count{}[1m]) > 0)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflows Execution Rate | Status: Early Exit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workflowName) (\n  increase(\n    platform_engine_workflow_earlyexit_time_seconds_count{}[1m]\n  )\n) / (\n  sum by (workflowName) (\n    increase(\n      platform_engine_workflow_completed_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_earlyexit_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_error_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_timeout_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Early Exit Workflows by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "group by (workflowName, workflowID) (rate(platform_engine_workflow_earlyexit_time_seconds_count{}[1m]) > 0)",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflows Execution Rate | Status: Errored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workflowName) (\n  increase(\n    platform_engine_workflow_error_time_seconds_count{}[1m]\n  )\n) / (\n  sum by (workflowName) (\n    increase(\n      platform_engine_workflow_completed_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_earlyexit_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_error_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_timeout_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errored Workflows by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "group by (workflowName, workflowID) (rate(platform_engine_workflow_error_time_seconds_count{}[1m]))",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Workflows Execution Rate | Status: Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (workflowName) (\n  increase(\n    platform_engine_workflow_timeout_time_seconds_count{}[1m]\n  )\n) / (\n  sum by (workflowName) (\n    increase(\n      platform_engine_workflow_completed_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_earlyexit_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_error_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  ) + sum by (workflowName) (\n    increase(\n      platform_engine_workflow_timeout_time_seconds_count{}[1m]\n    ) or platform_engine_workflow_count{} * 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout Workflows by Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "group by (workflowName, workflowID) (rate(platform_engine_workflow_timeout_time_seconds_count{}[1m]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p95) | Status: Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, sum(increase(platform_engine_workflow_completed_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p99) | Status: Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(increase(platform_engine_workflow_completed_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p95) | Status: Early Exit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, sum(increase(platform_engine_workflow_earlyexit_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p99) | Status: Early Exit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(increase(platform_engine_workflow_earlyexit_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p95) | Status: Errored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, sum(increase(platform_engine_workflow_error_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p99) | Status: Errored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(increase(platform_engine_workflow_error_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p95) | Status: Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, sum(increase(platform_engine_workflow_timeout_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Execution Latency (p99) | Status: Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum(increase(platform_engine_workflow_timeout_time_seconds_bucket{}[1m])) by (le, workflowName, csa_public_key))) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Engine (Capabilities)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 } },
  {
   "title": "Capabilities",
   "type": "timeseries",
   "description": "Capabilities that running on the engine",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "group(platform_engine_capabilities_count_total{}) by (capabilityID)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capabilities per Workflow invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_count_total{}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  },
  {
   "title": "Total Read Capability invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 139 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_count_total{capabilityID=~\"read.*\"}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  },
  {
   "title": "Total Write Capability invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_count_total{capabilityID=~\"write.*\"}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  },
  {
   "title": "Capability Failures Increase per Workflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_failures_total{}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  },
  {
   "title": "Increase of Read Failures per Workflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_failures_total{capabilityID=~\"read.*\"}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  },
  {
   "title": "Increase of Write Failures per Workflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum by (capabilityID, workflowID) (increase(platform_engine_capabilities_failures_total{capabilityID=~\"write.*\"}[$__range]))",
     "legendFormat": "{{capabilityID}}"
    }
   ]
  }
 ]
}