{
 "title": "Reorg network",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DAGs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch zero DAG",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{app=~\"ethereum-geth-.*\"} |= \"Generating DAG in progress               epoch=0\" | regexp \"(?P<timestamp>\\\\[.*\\\\])\" | logfmt | line_format \"{{.timestamp}}   perc={{.percentage}} from={{.container}}-{{.miner}}\""
      }
     ]
    }
   ]
  },
  { "title": "Chainlink nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CL Node",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{app=~\"chainlink-.*\"} |= \"HeadTracker: Received new head\" | logfmt | line_format \"head={{.blockHeight}}   hash={{.blockHash}}   parentHead={{.parentHeadHash}}\""
    }
   ]
  },
  { "title": "Block compare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Block hashes by miner",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app =~ \"ethereum-geth-.*\"} |= \"mined potential block\" | regexp \"(?P<message>\\\\[.*\\\\])\"| logfmt | line_format \"{{.message}}     block={{.number}}    {{.hash}}    from={{.container}}-{{.miner}}\""
    }
   ]
  },
  {
   "title": "Chaos daemons",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_component=\"chaos-daemon\"}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Tx node errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{tx=\"0\"} |= \"err=\" | logfmt | err != \"nil\""
    }
   ]
  },
  {
   "title": "Miner nodes errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"ethereum-geth-miner\"} |= \"err=\" | logfmt | err != \"nil\""
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tx node canonical",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{tx=\"0\"} |= \"block reached canonical chain\""
      }
     ]
    },
    {
     "title": "Miner-0 node canonical",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "{miner=\"0\"} |= \"block reached canonical chain\""
      }
     ]
    },
    {
     "title": "Tx node potential block",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{tx=\"0\"} |= \"mined potential block\""
      }
     ]
    },
    {
     "title": "Tx node potential block",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "{miner=\"0\"} |= \"mined potential block\""
      }
     ]
    }
   ]
  }
 ]
}