{
 "title": "DF Soak",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Soak Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Attempts",
   "type": "timeseries",
   "description": "Transaction Attempts",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time(\n  {job=\"ctf\"} |= \"Sending transaction\" [1s]\n)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "description": "Stats",
   "gridPos": { "h": 20, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(\n  {job=\"ctf\"} |= \"sent transaction\" [$__range]\n)) by (job)",
     "legendFormat": "Total TX Sent"
    },
    {
     "expr": "sum(count_over_time(\n  {job=\"ctf\"} |= \"Sending transaction\" [$__range]\n)) by (job)",
     "legendFormat": "Total TX Attempts"
    }
   ]
  },
  {
   "title": "Sent transactions",
   "type": "timeseries",
   "description": "Sent transactions",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time(\n  {job=\"ctf\"} |= \"sent transaction\" [1s]\n)",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".*don.*|.*fake.*\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".*don.*|.*fake.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*don.*|.*fake.*\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".*don.*|.*fake.*\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions",
     "type": "logs",
     "description": "Transactions",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "{job=\"ctf\"} |= \"sent transaction\""
      }
     ]
    },
    {
     "title": "P2P Discovery Report",
     "type": "logs",
     "description": "P2P Discovery Report",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "{job=\"ctf\"} |= \"DiscoveryProtocol: Status report\""
      }
     ]
    }
   ]
  },
  { "title": "Gas Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } }
 ]
}