{
 "title": "WASP (VictoriaLogs)",
 "tags": [
  "generated",
  "load-test",
  "wasp",
  "victorialogs"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "go_test_name",
    "label": "Go test name",
    "query": {}
   },
   {
    "name": "gen_name",
    "label": "Generator name",
    "query": {}
   },
   {
    "name": "call_group",
    "label": "Call group",
    "query": {}
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": {}
   },
   {
    "name": "commit",
    "label": "Commit",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "WASP Load Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(current_rps) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    }
   ]
  },
  {
   "title": "VUs (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(current_instances) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:responses | stats by (go_test_name, gen_name) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} Responses/sec"
    }
   ]
  },
  {
   "title": "Successful requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses AND NOT _msg:\"\\\"failed\\\":true\" | stats by (go_test_name, gen_name) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} Successful requests"
    }
   ]
  },
  {
   "title": "Errored requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses AND _msg:\"\\\"failed\\\":true\" | stats by (go_test_name, gen_name) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} Errored requests"
    }
   ]
  },
  {
   "title": "Timed out requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses AND _msg:\"\\\"timeout\\\":true\" | stats by (go_test_name, gen_name) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} Timed out requests"
    }
   ]
  },
  {
   "title": "RPS/VUs per schedule segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(current_rps) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(current_instances) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses | stats by (go_test_name, gen_name, call_group) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} responses/sec"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:responses | stats by (go_test_name, gen_name) count() value",
     "legendFormat": "{{go_test_name}} {{gen_name}} Total responses/sec"
    }
   ]
  },
  {
   "title": "Latency quantiles over groups (99, 95, 50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses | unpack_json | stats by (go_test_name, gen_name, call_group) quantile(0.99, duration) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} Q 99"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses | unpack_json | stats by (go_test_name, gen_name, call_group) quantile(0.95, duration) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} Q 95"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses | unpack_json | stats by (go_test_name, gen_name, call_group) quantile(0.5, duration) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} Q 50"
    }
   ]
  },
  {
   "title": "Responses latencies by types over time (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND call_group:~\"${call_group:pipe}\" AND test_data_type:responses | unpack_json | stats by (go_test_name, gen_name, call_group) max(duration) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}}"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:responses | unpack_json | stats by (go_test_name, gen_name) max(duration) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} all groups"
    }
   ]
  },
  { "title": "WASP Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latest segment stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" | stats sum_len(_msg) value",
     "legendFormat": "Overall logs size"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" | stats sum_len(_msg) value",
     "legendFormat": "Logs size per second"
    }
   ]
  },
  {
   "title": "CallResult sampling (successful results)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(samples_recorded) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} recorded"
    },
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats | unpack_json | stats by (go_test_name, gen_name) max(samples_skipped) value",
     "legendFormat": "{{go_test_name}} {{gen_name}} skipped"
    }
   ]
  },
  {
   "title": "Stats logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:stats"
    }
   ]
  },
  {
   "title": "Failed responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:responses AND _msg:\"\\\"failed\\\":true\""
    }
   ]
  },
  {
   "title": "Timed out responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "go_test_name:~\"${go_test_name:pipe}\" AND gen_name:~\"${gen_name:pipe}\" AND test_data_type:responses AND _msg:\"\\\"timeout\\\":true\""
    }
   ]
  }
 ]
}