{
 "title": "CL Node Errors",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Err/Wrn Count",
   "type": "timeseries",
   "description": "Err/Wrn Count",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ctf\", container=~\".*node.*\"} \n  | json \n  | level=\"error\" [$__interval])) by (logger)",
     "legendFormat": "ERR {{logger}}"
    },
    {
     "expr": "sum(count_over_time({job=\"ctf\", container=~\".*node.*\"} \n  | json \n  | level=\"warn\" [$__interval])) by (logger)",
     "legendFormat": "WRN {{logger}}"
    }
   ]
  },
  {
   "title": "Err/Wrn Distribution",
   "type": "piechart",
   "description": "Err/Wrn Distribution",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"ctf\", container=~\".*node.*\"} \n  | json \n  | level=\"error\" [$__interval])) by (logger)",
     "legendFormat": "ERR {{logger}}"
    },
    {
     "expr": "sum(count_over_time({job=\"ctf\", container=~\".*node.*\"} \n  | json \n  | level=\"warn\" [$__interval])) by (logger)",
     "legendFormat": "WRN {{logger}}"
    }
   ]
  },
  {
   "title": "Node Errors",
   "type": "logs",
   "description": "Node Errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"ctf\", container=~\".*node.*\"}\n  | json \n  | level=\"error\" \n  | logfmt \n  | line_format \"{{.container }} {{.logger }} {{.msg }} {{.err}}\""
    }
   ]
  },
  {
   "title": "Node Warnings",
   "type": "logs",
   "description": "Node Warnings",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"ctf\", container=~\".*node.*\"} \n  | json \n  | level=\"warn\" \n  | logfmt \n  | line_format \"{{.container }} {{.logger }} {{.msg }} {{.err}}\""
    }
   ]
  }
 ]
}