{
 "title": "Chainlink Testing Insights",
 "description": "A look at the components of Chainlink Integration tests",
 "tags": [ "tests" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "cl_node",
    "label": "Chainlink Node",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "geth_node",
    "label": "Simulated Geth Node",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Components health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Components health",
     "type": "stat",
     "description": "Components health",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "health{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "service: {{service_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overall metrics across all CL nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall log count by type",
     "type": "timeseries",
     "description": "Overall log count by type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "log_error_count{namespace=\"$namespace\"}",
       "legendFormat": "WARN, pod: {{pod}}"
      },
      {
       "expr": "log_warn_count{namespace=\"$namespace\"}",
       "legendFormat": "ERROR, pod: {{pod}}"
      },
      {
       "expr": "log_panic_count{namespace=\"$namespace\"}",
       "legendFormat": "PANIC, pod: {{pod}}"
      },
      {
       "expr": "log_critical_count{namespace=\"$namespace\"}",
       "legendFormat": "CRITICAL, pod: {{pod}}"
      },
      {
       "expr": "log_fatal_count{namespace=\"$namespace\"}",
       "legendFormat": "FATAL, pod: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline tasks ($cl_node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipeline tasks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pipeline_tasks_total_finished{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "type: {{task_type}}, jobID: {{job_id}}, status: {{status}}"
      }
     ]
    },
    {
     "title": "Queued tasks and pipelines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pipeline_task_runs_queued{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Tasks"
      },
      {
       "expr": "pipeline_runs_queued{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Pipelines"
      }
     ]
    },
    {
     "title": "Pipeline avg time to completion",
     "type": "timeseries",
     "description": "Pipeline avg time to completion",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "pipeline_run_total_time_to_completion{namespace=\"$namespace\", pod=\"$cl_node\"} * 1e-6",
       "legendFormat": "jobID: {{job_id}}"
      }
     ]
    },
    {
     "title": "Pipeline fetch avg bytes",
     "type": "timeseries",
     "description": "Pipeline fetch avg bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "pipeline_task_http_response_body_size{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Task type: {{pipeline_task_spec_id}}"
      }
     ]
    },
    {
     "title": "Task execution time by type",
     "type": "timeseries",
     "description": "Task execution time by type",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "pipeline_task_execution_time{namespace=\"$namespace\", pod=\"$cl_node\"} * 1e-6",
       "legendFormat": "type: {{task_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EVM CL node metrics ($cl_node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "EVM node polls",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_polls_success{namespace=\"$namespace\", pod=\"$cl_node\"} [2m])"
      }
     ]
    },
    {
     "title": "RPC calls hist",
     "type": "timeseries",
     "description": "RPC calls hist",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{pod=\"$cl_node\", rpcCallName=\"CallContext\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "CallContext - 95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{pod=\"$cl_node\", rpcCallName=\"CallContext\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "CallContext - 50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BatchCallContext\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "BatchCallContext - 95"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BatchCallContext\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "BatchCallContext - 50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BalanceAt\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "BalanceAt - 95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"BalanceAt\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "BalanceAt - 50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"PendingNonceAt\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "PendingNonceAt - 95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(evm_pool_rpc_node_rpc_call_time_bucket{rpcCallName=\"PendingNonceAt\"}[2m])) by (le)) * 1e-6",
       "legendFormat": "PendingNonceAt - 50"
      }
     ]
    },
    {
     "title": "RPC node states",
     "type": "timeseries",
     "description": "RPC node states",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "evm_pool_rpc_node_states{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "chainId: {{evmChainID}} pod: {{pod}} state: {{state}}"
      }
     ]
    },
    {
     "title": "RPC node alive statuses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "evm_pool_rpc_node_num_transitions_to_alive{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "chainId: {{evmChainID}} pod: {{pod}}"
      }
     ]
    },
    {
     "title": "RPC calls total (rate)",
     "type": "timeseries",
     "description": "RPC calls total (rate)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_calls_total{namespace=\"$namespace\", pod=\"$cl_node\"}[2m])"
      }
     ]
    },
    {
     "title": "Total verifications (success/errors)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(evm_pool_rpc_node_verifies{namespace=\"$namespace\", pod=\"$cl_node\"} [2m])",
       "legendFormat": "Success, chainId: {{evmChainID}} nodeName: {{nodeName }} instance: {{instance}}"
      },
      {
       "expr": "rate(evm_pool_rpc_node_verifies_success{namespace=\"$namespace\", pod=\"$cl_node\"} [2m])",
       "legendFormat": "Total, chainId: {{evmChainID}} nodeName: {{nodeName }} instance: {{instance}}"
      }
     ]
    },
    {
     "title": "ETH account value",
     "type": "timeseries",
     "description": "ETH account value",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "eth_balance{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "account: {{account}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TX manager ($cl_node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "TXns count (confirmed/unconfirmed)",
     "type": "timeseries",
     "description": "TXns count (confirmed/unconfirmed)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "unconfirmed_transactions{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Unconfirmed, Pod: {{pod}}"
      },
      {
       "expr": "tx_manager_num_confirmed_transactions{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Confirmed, Pod: {{pod}}"
      },
      {
       "expr": "tx_manager_num_successful_transactions{namespace=\"$namespace\", pod=\"$cl_node\"}",
       "legendFormat": "Successful, Pod: {{pod}}"
      }
     ]
    },
    {
     "title": "TXns times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(tx_manager_time_until_tx_confirmed_bucket [2m])) by (le)) * 1e-6",
       "legendFormat": "TxConfirmed - 95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tx_manager_time_until_tx_confirmed_bucket [2m])) by (le)) * 1e-6",
       "legendFormat": "TxConfirmed - 50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tx_manager_time_until_tx_broadcast_bucket [2m])) by (le)) * 1e-6",
       "legendFormat": "TxBroadcast -95"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(tx_manager_time_until_tx_broadcast_bucket [2m])) by (le)) * 1e-6",
       "legendFormat": "TxBroadcast -50"
      }
     ]
    }
   ]
  },
  {
   "title": "CL node metrics ($cl_node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "cl_node",
   "collapsed": true,
   "panels": [
    {
     "title": "Chainlink Node Logs",
     "type": "logs",
     "description": "All logs of the Chainlink node",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}"
      }
     ]
    },
    {
     "title": "Chainlink Node Errors",
     "type": "logs",
     "description": "All [ERROR] logs from the Chainlink node.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"} | json | level=~\"error|crit\""
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Chainlink CPU usage and limit",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"node\", pod=\"$cl_node\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "timeseries",
     "description": "Chainlink RAM usage and limit",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{container=\"node\", pod=\"$cl_node\", resource=\"memory\"} / 1024 / 1024",
       "legendFormat": "Limits, container: {{container}} pod: {{pod}}"
      },
      {
       "expr": "container_memory_usage_bytes{container=\"node\", pod=\"$cl_node\"} / 1024 / 1024",
       "legendFormat": "Used, container: {{container}} pod: {{pod}}"
      }
     ]
    },
    {
     "title": "Chainlink Node Warnings",
     "type": "logs",
     "description": "All [WARN] logs from the Chainlink node.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"node\", pod=\"$cl_node\"}  | json | level=~\"warn\" | msg!=\"Disk space is not enough to log into disk any longer, required disk space\""
      }
     ]
    }
   ]
  },
  {
   "title": "Simulated network metrics ($geth_node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "geth_node",
   "collapsed": true,
   "panels": [
    {
     "title": "Geth Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=~\"geth-network|starknetdev\", pod=\"$geth_node\"}"
      }
     ]
    },
    {
     "title": "Geth CPU",
     "type": "timeseries",
     "description": "Geth CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"geth-network\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=~\"geth-network|starknetdev\"}"
      }
     ]
    },
    {
     "title": "Geth RAM",
     "type": "timeseries",
     "description": "Geth RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=~\"geth-network|starknetdev\", resource=\"memory\"} / 1024 / 1024"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=~\"geth-network|starknetdev\"} / 1024 / 1024"
      }
     ]
    }
   ]
  },
  {
   "title": "Mock Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mock Server Logs",
     "type": "logs",
     "description": "Logs of the mockserver",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"mockserver\"}"
      }
     ]
    },
    {
     "title": "Mock Server CPU",
     "type": "timeseries",
     "description": "Mock Server CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"mockserver\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"mockserver\"}"
      }
     ]
    },
    {
     "title": "Mock Server RAM",
     "type": "timeseries",
     "description": "Mock Server RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"mockserver\", resource=\"memory\"} / 1024 / 1024"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"mockserver\"} / 1024 / 1024"
      }
     ]
    }
   ]
  },
  {
   "title": "Test runner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test Runner Logs",
     "type": "logs",
     "description": "Logs of the instance actually running the tests",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"}"
      }
     ]
    },
    {
     "title": "Runner CPU",
     "type": "timeseries",
     "description": "Test Runner CPU usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"remote-test-runner\", resource=\"cpu\"}"
      },
      {
       "expr": "container_cpu_load_average_10s{namespace=\"$namespace\", container=\"remote-test-runner\"}"
      }
     ]
    },
    {
     "title": "Runner RAM",
     "type": "timeseries",
     "description": "Test Runner RAM usage and limit",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"remote-test-runner\", resource=\"memory\"} / 1024 / 1024"
      },
      {
       "expr": "container_memory_usage_bytes{namespace=\"$namespace\", container=\"remote-test-runner\"} / 1024 / 1024"
      }
     ]
    },
    {
     "title": "Test Runner Errors and Warnings",
     "type": "logs",
     "description": "Errors and Warnings found in Test Runner",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |~ \"WRN|ERR\""
      }
     ]
    },
    {
     "title": "Test Runner Info",
     "type": "logs",
     "description": "Info logs",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |= \"INF\""
      }
     ]
    },
    {
     "title": "Test Runner Debugs",
     "type": "logs",
     "description": "Debugs",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", container=\"remote-test-runner\"} |~ \"DBG\""
      }
     ]
    }
   ]
  }
 ]
}