{
 "title": "WASP (Loki)",
 "tags": [
  "generated",
  "load-test",
  "wasp",
  "loki"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "go_test_name",
    "label": "Go test name",
    "query": {}
   },
   {
    "name": "gen_name",
    "label": "Generator name",
    "query": {}
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": {}
   },
   {
    "name": "commit",
    "label": "Commit",
    "query": {}
   },
   {
    "name": "call_group",
    "label": "Call group",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "WASP Load Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_rps [10s]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    }
   ]
  },
  {
   "title": "VUs (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_instances [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Now)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} [1s])) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} Responses/sec"
    }
   ]
  },
  {
   "title": "Successful requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap success [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} Successful requests"
    }
   ]
  },
  {
   "title": "Errored requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap failed [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} Errored requests"
    }
   ]
  },
  {
   "title": "Timed out requests (Total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap callTimeout [$__range]) by (node_id, go_test_name, gen_name)) by (__stream_shard__)",
     "legendFormat": "{{go_test_name}} {{gen_name}} Timed out requests"
    }
   ]
  },
  {
   "title": "RPS/VUs per schedule segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_rps [$__interval]) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} RPS"
    },
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_rps [$__interval]) by (node_id, go_test_name, gen_name))",
     "legendFormat": "{{go_test_name}} Total RPS"
    },
    {
     "expr": "max_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_instances [$__interval]) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} VUs"
    },
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap current_instances [$__interval]) by (node_id, go_test_name, gen_name))",
     "legendFormat": "{{go_test_name}} Total VUs"
    }
   ]
  },
  {
   "title": "Responses/sec (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\", call_group=~\"${call_group:pipe}\"} [1s])) by (node_id, go_test_name, gen_name, call_group)",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} responses/sec"
    },
    {
     "expr": "sum(count_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} [1s])) by (node_id, go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} Total responses/sec"
    }
   ]
  },
  {
   "title": "Latency quantiles over groups (99, 95, 50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 99 - {{error}}"
    },
    {
     "expr": "quantile_over_time(0.95, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 95 - {{error}}"
    },
    {
     "expr": "quantile_over_time(0.50, {branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap duration [$__interval]) by (go_test_name, gen_name) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} Q 50 - {{error}}"
    }
   ]
  },
  {
   "title": "Responses latencies by types over time (Generator, CallGroup)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\", call_group=~\"${call_group}\"}\n| json\n| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} {{call_group}} T: {{timeout}} E: {{error}}"
    },
    {
     "expr": "last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap duration [$__interval]) / 1e6",
     "legendFormat": "{{go_test_name}} {{gen_name}} all groups T: {{timeout}} E: {{error}}"
    }
   ]
  },
  { "title": "WASP Debug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latest segment stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", gen_name=~\"${gen_name:pipe}\"} [$__range]) * 1e-6)",
     "legendFormat": "Overall logs size"
    },
    {
     "expr": "sum(bytes_rate({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", gen_name=~\"${gen_name:pipe}\"} [$__interval]) * 1e-6)",
     "legendFormat": "Logs size per second"
    }
   ]
  },
  {
   "title": "CallResult sampling (successful results)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap samples_recorded [$__interval])) by (go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} recorded"
    },
    {
     "expr": "sum(last_over_time({branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}\n| json\n| unwrap samples_skipped [$__interval])) by (go_test_name, gen_name)",
     "legendFormat": "{{go_test_name}} {{gen_name}} skipped"
    }
   ]
  },
  {
   "title": "Stats logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"stats\", gen_name=~\"${gen_name:pipe}\"}"
    }
   ]
  },
  {
   "title": "Failed responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} |~ \"failed\\\":true\""
    }
   ]
  },
  {
   "title": "Timed out responses",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "{branch=~\"${branch:pipe}\", commit=~\"${commit:pipe}\", go_test_name=~\"${go_test_name:pipe}\", test_data_type=~\"responses\", gen_name=~\"${gen_name:pipe}\"} |~ \"timeout\\\":true\""
    }
   ]
  }
 ]
}