name: Analyze API Changes

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  api-diff:
    uses: smartcontractkit/.github/.github/workflows/reusable-apidiff-go-analysis.yml@reusable-apidiff-go-analysis/v1
    with:
      file-patterns: |
        **/*.go
        **/go.mod
        **/go.sum
      module-patterns: |
        **
        !**/examples/**
      enforce-compatible: false
