name: Grafana Alertcheck Release

on:
  push:
    tags:
      - grafana-alertcheck/v*

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    environment: integration
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: ./grafana-alertcheck/go.mod
          cache-dependency-path: ./grafana-alertcheck/go.mod
      - name: Goreleaser Release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser-pro
          version: "~> v2"
          args: release --clean -f ./grafana-alertcheck/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
