name: Module graph
on:
  pull_request:
jobs:
  modgraph:
    runs-on: ubuntu-latest
    name: modgraph
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@v5
      - run: make modgraph
      - name: Ensure clean modgraph
        run: git diff --minimal --exit-code
