name: Validate GHA Workflows
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: Validate GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Run actionlint
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1