name: Validate GHA Workflows
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: Validate GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run actionlint
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1.57.0