name: Validate GHA Workflows
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: Validate GitHub Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run actionlint
        uses: reviewdog/action-actionlint@7eeec1dd160c2301eb28e1568721837d084558ad # v1.57.0